{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-02-16\n",
      "Conexión exitosa\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<string>:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "vhc_corregida_can\n",
      "SE CONECTO BIEN\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<string>:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "vhc_corregida_gps\n"
     ]
    }
   ],
   "source": [
    "import queries_km_servicio_diario as qr\n",
    "import psycopg2\n",
    "import pandas as pd\n",
    "import numpy as np  \n",
    "import xlsxwriter\n",
    "from datetime import datetime, timedelta,date\n",
    "import copy\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\", category=UserWarning, module=\"pandas\")\n",
    "pd.set_option('display.max_columns', None)\n",
    "inicio_d = datetime.today().date() - timedelta(days = 1)\n",
    "fin_d    = datetime.today().date()# - timedelta(days = 1)\n",
    "#%run \"validacion_km_diario_oficial_reproceso_3.ipynb\"\n",
    "import nbformat\n",
    "with open(\"C:\\\\Users\\\\Tomas Retamal\\\\OneDrive - BUSES HUALPEN\\\\Documentos\\\\Proyectos\\\\TomasRetamal\\\\Opti\\\\KM Vacío\\\\KM Pablo\\\\validacion_km_diario_oficial_reproceso_3.ipynb\", encoding=\"utf8\") as f:\n",
    "    nb2 = nbformat.read(f, as_version=4)\n",
    "\n",
    "for cell2 in nb2.cells:\n",
    "    if cell2.cell_type == \"code\":\n",
    "        exec(cell2.source)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "fecha_inicial = inicio_d.strftime(\"%Y-%m-%d\")\n",
    "fecha_fin = fin_d.strftime(\"%Y-%m-%d\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Definición de directorios"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "#dir = r\"C:\\Users\\Richard Salgado\\Desktop\\Kilometraje\\Kilometraje_total\\Kilometraje_consolidado\\Kilometraje_oficial_septiembre\"\n",
    "#dir = r'C:\\Users\\Tomas Retamal\\OneDrive - BUSES HUALPEN\\Documentos\\Proyectos\\TomasRetamal\\Opti\\KM Vacío\\KM Pablo'\n",
    "dir = r'C:\\Users\\Tomas Retamal\\OneDrive - BUSES HUALPEN\\Documentos\\Proyectos\\PabloJerez\\respaldo\\Kilometraje\\Kilometraje_total\\Kilometraje_consolidado\\Kilometraje_oficial_septiembre\\validaciones_individuales_reproceso_2'\n",
    "# output\n",
    "# dir = dir + r'\\validaciones_individuales_reproceso_2'\n",
    "dir_out_val_can = rf'{dir}\\validacion_can_{fecha_inicial}_{fecha_fin}.xlsx'\n",
    "dir_out_val_gps = rf'{dir}\\validacion_gps_{fecha_inicial}_{fecha_fin}.xlsx'\n",
    "dir_out_val_comb = rf'{dir}\\validacion_comb_{fecha_inicial}_{fecha_fin}.xlsx'\n",
    "dir_out_val_tall = rf'{dir}\\validacion_taller_{fecha_inicial}_{fecha_fin}.xlsx'\n",
    "dir_out_val_chl = rf'{dir}\\validacion_checklist_{fecha_inicial}_{fecha_fin}.xlsx'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Parte heredada de Pablo\n",
    "cc = 'Unnamed: 0'\n",
    "reportes_1=pd.read_excel(rf'{dir}\\validacion_gps_{fecha_inicial}_{fecha_fin}.xlsx','Comparacion')\n",
    "del reportes_1[cc]\n",
    "validacion_gps=reportes_1.values.tolist()\n",
    "\n",
    "reportes_3=pd.read_excel(rf'{dir}\\validacion_can_{fecha_inicial}_{fecha_fin}.xlsx','Comparacion')\n",
    "del reportes_3[cc]\n",
    "reportes_3['numero_interno'] = reportes_3['numero_interno'].apply(lambda x: x.strip().split(' ')[0] if type(x)==str else x)\n",
    "validacion_can=reportes_3.values.tolist()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Funciones viajes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "def etiquetar_errores(x):\n",
    "    velocidad = 150\n",
    "    if float(x.viaje_distancia_gps) < 0 or float(x.viaje_distancia_can) < 0:\n",
    "        x.etiqueta = 'Negativo'\n",
    "    elif float(x.viaje_distancia_gps) > 2000 or float(x.viaje_distancia_can) > 2000:\n",
    "        x.etiqueta = 'Excesivo'\n",
    "    elif ((x.viaje_fecha_termino_real - x.viaje_fecha_inicio_real).total_seconds() / 3600) * velocidad < x.viaje_distancia_can or ((x.viaje_fecha_termino_real - x.viaje_fecha_inicio_real).total_seconds()/3600)*velocidad < x.viaje_distancia_gps:\n",
    "        x.etiqueta = 'Excesivo'\n",
    "    \n",
    "    else:\n",
    "        if pd.isna(x.viaje_km_inicial_gps) == True or pd.isna(x.viaje_km_final_gps) == True:\n",
    "            \n",
    "            if pd.isna(x.viaje_km_inicial_can)==True or pd.isna(x.viaje_km_final_can) == True:\n",
    "                x.etiqueta = 'Faltante gps y faltante can'\n",
    "            else:\n",
    "                x.etiqueta = 'Faltante gps'\n",
    "\n",
    "        else:\n",
    "            if pd.isna(x.viaje_km_inicial_can)==True or pd.isna(x.viaje_km_final_can) == True:\n",
    "                x.etiqueta = 'Existe gps y faltante can'\n",
    "            else:\n",
    "                x.etiqueta = 'Existe gps y existe can'\n",
    "    return x"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Obtener viajes y sus observaciones"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Función hecha por Pablo\n",
    "def obtener_viajes_con_obs(fecha_ini,fecha_fin):\n",
    "    conn_sql = psycopg2.connect(user = \"tretamal\",\n",
    "                            password = \"LrtA0XYloG\",\n",
    "                            host = \"192.168.40.239\",\n",
    "                            port = \"5432\",\n",
    "                            database = \"bidb\",\n",
    "                            options=\"-c search_path=dbo,taller\")\n",
    "\n",
    "    # Obtención de viajes desde bidb\n",
    "    df = pd.read_sql(qr.query_viajes_bidb(str(inicio_d), str(fin_d)), conn_sql)\n",
    "    df[\"viaje_id\"] = df[\"viaje_id\"].astype(\"int64\")\n",
    "    df['etiqueta'] = None\n",
    "    df = df.apply(lambda x: etiquetar_errores(x), axis = 1)\n",
    "    conn_sql = psycopg2.connect(user = \"cons_paul\",\n",
    "                                password = \"DoNPau2746l\",\n",
    "                                host = \"db-hualpen-com-reader.cm5wbxahj6z3.us-east-2.rds.amazonaws.com\",\n",
    "                                port = \"5432\",\n",
    "                                database = \"hualpen_ser2_prod\")\n",
    "    # Obtención de viajes con observaciones desde cursor\n",
    "    df_3= pd.read_sql(qr.query_observaciones(str(inicio_d), str(fin_d)), conn_sql)\n",
    "\n",
    "    # merge entre viajes bidb y viajes con observaciones\n",
    "    viajes_con_obs = pd.merge(df,df_3,on = 'viaje_id', how = 'left')\n",
    "\n",
    "    # las observaciones traidas son las correspondientes a cambios de móvil\n",
    "    # nos interesa saber cuándo ocurrió el cambio\n",
    "    viajes_con_obs[\"momento_cambio_movil\"] = pd.Series(dtype='str')\n",
    "    viajes_con_obs[\"momento_cambio_movil\"] = viajes_con_obs.apply(lambda x: \"Antes del viaje\" if (x.fecha_creacion < x.viaje_fecha_inicio_real) else \"Durante el viaje\" if (x.fecha_creacion > x.viaje_fecha_inicio_real) else None, axis = 1)\n",
    "    viajes_con_obs = viajes_con_obs.sort_values([\"viaje_id\", \"fecha_creacion\"], ignore_index=True)\n",
    "\n",
    "    # puede haber más de una observación por viaje, lo que genera registros duplicados\n",
    "    # los eliminamos quedándonos con el registro de la observación más reciente\n",
    "    viajes_con_obs.drop_duplicates(subset = [\"viaje_id\"], keep = \"last\", inplace = True)\n",
    "    viajes_con_obs = viajes_con_obs.reset_index(drop=True)\n",
    "    \n",
    "    return viajes_con_obs\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Obtener viajes de dos días\n",
    "\n",
    "En esta función, obtenemos solo los viajes que terminan al día siguiente (desde los viajes obtenidos en celda anterior)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [],
   "source": [
    "def viajes_dos_dias(df):\n",
    "    df[\"flag_planificado\"] = df.apply(lambda x: 1 if ((x.viaje_fecha_inicio.date() != x.viaje_fecha_termino.date()) and ((x.viaje_fecha_termino.time().hour + x.viaje_fecha_termino.time().minute) != 0)) else 0, axis = 1)\n",
    "    df[\"flag_real\"]        = df.apply(lambda x: 1 if ( (pd.isna(x.viaje_fecha_inicio_real.date()) == False) and (pd.isna(x.viaje_fecha_termino_real.date()) == False) and ((x.viaje_fecha_termino_real.date() - x.viaje_fecha_inicio_real.date()).days == 1) and ((x.viaje_fecha_termino_real.time().hour + x.viaje_fecha_termino_real.time().minute) != 0)) else 0, axis = 1)\n",
    "    df_dos_dias = df[(df[\"flag_real\"] == 1)].reset_index(drop = True)\n",
    "    return df_dos_dias"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Odometro medianoche (can y gps)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [],
   "source": [
    "def odometro_medianoche_can(df,fecha_ini, fecha_fin):\n",
    "    #df[\"id_numero_interno\"] = df.apply(lambda x: str(x.id) + x.numero_interno, axis = 1)\n",
    "    conn_sql = psycopg2.connect(user = \"cons_paul\",\n",
    "                                    password = \"DoNPau2746l\",\n",
    "                                    host = \"db-hualpen-com-reader.cm5wbxahj6z3.us-east-2.rds.amazonaws.com\",\n",
    "                                    port = \"5432\",\n",
    "                                    database = \"hualpen_com_prod\")\n",
    "    lista_odometros_medianoche_can_fin = []\n",
    "    fuente_odometro_medianoche_can = []\n",
    "    hora_evento_can = []\n",
    "    moviles = []\n",
    "    ids = []\n",
    "    for index, row in df_dos_dias.iterrows():\n",
    "        #print(movil)\n",
    "        aux = vhc_corregida_can[(vhc_corregida_can[\"numero_interno\"] == row[\"movil_numero_interno\"]) &  (vhc_corregida_can[\"fecha_inicio\"] == pd.to_datetime(str(row[\"viaje_fecha_termino_real\"].date()) + \" 00:00:00\", format = \"%Y-%m-%d %H:%M:%S\"))].sort_values(\"fecha_inicio\").reset_index(drop = True)\n",
    "        ## si en vhc no existe el dato, vamos a buscarlo a evento telemetría\n",
    "        cursor = conn_sql.cursor()\n",
    "        # si el movil no está en vhc (df vacío), nos saltamos el dato\n",
    "        try:\n",
    "            a = pd.isna(aux.iloc[0][\"can_inicio\"]) # si aquí hay un error, significa que el df aux es vacío, es decir, el dato que buscamos no está en vhc\n",
    "            # si a es true, debo ingresar a query_eventos\n",
    "            # si a es false, no ingreso a query eventos\n",
    "            # si hay un error, a no tiene valor, por lo que hay que asignárselo en el except\n",
    "            # en dicho caso, el valor que se le asigna a a es irrelevante, ya que el error\n",
    "            # implica que aux es vacío, por lo que sí o sí se entrará a quey_eventos.\n",
    "            # Arbitrariamente la asignaré a false \n",
    "        except:\n",
    "            a = False\n",
    "        if aux.empty or a:\n",
    "            command_set_timezone = '''\n",
    "            set time zone 'America/Santiago'\n",
    "            '''    \n",
    "            query_eventos = '''\n",
    "            select v.nombre \n",
    "            ,et.fecha_evento\n",
    "            ,(et.atributos::json-> 'senial'->>'odom_km')::decimal as odometro_can\n",
    "            ,case\n",
    "                when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),12,1) = '2' then to_timestamp(concat(et.fecha_evento::date + 1, ' 00:00:00'), 'YYYY-MM-DD HH24:MI:SS') - et.fecha_evento\n",
    "                when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),12,1) = '0' then et.fecha_evento - to_timestamp(concat(et.fecha_evento::date    , ' 00:00:00'), 'YYYY-MM-DD HH24:MI:SS')\n",
    "            --    when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),13,1) = '0' then to_timestamp(concat(et.fecha_evento::date, ' 21:00:00'), 'YYYY-MM-DD HH24:MI:SS') - et.fecha_evento\n",
    "            --    when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),13,1) = '1' then et.fecha_evento - to_timestamp(concat(et.fecha_evento::date    , ' 21:00:00'), 'YYYY-MM-DD HH24:MI:SS')\n",
    "            end diferencia_medianoche\n",
    "            from evento_telemetria et \n",
    "            left join vehiculo v on et.vehiculo_id =v.id \n",
    "            where et.fecha_evento >= '{}' and et.fecha_evento < '{}'\n",
    "            and v.nombre = '{}'\n",
    "            order by diferencia_medianoche\n",
    "            '''.format(str(row[\"viaje_fecha_inicio_real\"].date()) + \" 23:50:00\", str(row[\"viaje_fecha_termino_real\"].date()) + \" 00:10:00\", row[\"movil_numero_interno\"])#format(str(row[\"fecha_inicio_real\"].date()) + \" 20:50:00\", str(row[\"fecha_inicio_real\"].date()) + \" 21:10:00\", row[\"numero_interno\"])\n",
    "            # .format(str(row[\"fecha_inicio_real\"].date()) + \" 23:50:00\", str(row[\"fecha_termino_real\"].date()) + \" 00:10:00\", row[\"numero_interno\"])\n",
    "            cursor.execute(command_set_timezone)\n",
    "            df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
    "            cursor.close()\n",
    "                # me quedo con todos los registros que sí tienen odometro can\n",
    "            df_eventos_filtrado = df_eventos[pd.isna(df_eventos[\"odometro_can\"]) == False]\n",
    "            # si al aplicar el filtro el df queda vacío, no hay odómetro, por lo que guardamos None\n",
    "            if df_eventos_filtrado.empty:\n",
    "                lista_odometros_medianoche_can_fin.append(None)\n",
    "                fuente_odometro_medianoche_can.append(None)\n",
    "                hora_evento_can.append(None)\n",
    "            else:\n",
    "                lista_odometros_medianoche_can_fin.append(df_eventos_filtrado.iloc[0][\"odometro_can\"])\n",
    "                fuente_odometro_medianoche_can.append(\"et\")\n",
    "                hora_evento_can.append(df_eventos_filtrado.iloc[0][\"fecha_evento\"])\n",
    "        else:\n",
    "            lista_odometros_medianoche_can_fin.append(aux.iloc[0][\"can_inicio\"])\n",
    "            fuente_odometro_medianoche_can.append(\"vhc\")\n",
    "            hora_evento_can.append(pd.to_datetime(fecha_fin + \" 00:00:00\"))\n",
    "        ids.append(row[\"viaje_id\"])\n",
    "        moviles.append(row[\"movil_numero_interno\"])\n",
    "        #ids.append(row[\"id\"])\n",
    "        #moviles.append(row[\"numero_interno\"])\n",
    "        \n",
    "    #data_medianoche = {'nombre': moviles, 'odometros_medianoche_can_dia_inicio': lista_odometros_medianoche_can_inicio, 'odometros_medianoche_can_dia_termino': lista_odometros_medianoche_can_fin}\n",
    "    data_medianoche_can = {'viaje_id':ids, 'movil_numero_interno': moviles, 'odometro_medianoche_can': lista_odometros_medianoche_can_fin, 'fuente_odometro_medianoche_can':fuente_odometro_medianoche_can, 'hora_evento_can_medianoche':hora_evento_can}\n",
    "    df_medianoche_can = pd.DataFrame(data_medianoche_can)\n",
    "    #df_medianoche[\"hora_evento_can_medianoche\"] = df_medianoche[\"hora_evento_can_medianoche\"].apply(lambda x: x.tz_localize(None) if pd.isna(x) == False else x)\n",
    "    #df_medianoche[\"hora_evento_gps_medianoche\"] = df_medianoche[\"hora_evento_gps_medianoche\"].apply(lambda x: x.tz_localize(None) if pd.isna(x) == False else x)\n",
    "\n",
    "    return df_medianoche_can # df_medianoche#, df_vhc#moviles_agendados_dos_dias, lista_odometros, lista_eventos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [],
   "source": [
    "def odometro_medianoche_gps(df,fecha_ini, fecha_fin):\n",
    "    #df[\"id_numero_interno\"] = df.apply(lambda x: str(x.id) + x.numero_interno, axis = 1)\n",
    "    conn_sql = psycopg2.connect(user = \"cons_paul\",\n",
    "                                    password = \"DoNPau2746l\",\n",
    "                                    host = \"db-hualpen-com-reader.cm5wbxahj6z3.us-east-2.rds.amazonaws.com\",\n",
    "                                    port = \"5432\",\n",
    "                                    database = \"hualpen_com_prod\")\n",
    "    lista_odometros_medianoche_gps_fin = []\n",
    "    fuente_odometro_medianoche_gps = []\n",
    "    hora_evento_gps = []\n",
    "    moviles = []\n",
    "    ids = []\n",
    "    for index, row in df_dos_dias.iterrows():\n",
    "        #print(movil)\n",
    "        aux = vhc_corregida_gps[(vhc_corregida_gps[\"numero_interno\"] == row[\"movil_numero_interno\"]) &  (vhc_corregida_gps[\"fecha_inicio\"] == pd.to_datetime(str(row[\"viaje_fecha_termino_real\"].date()) + \" 00:00:00\", format = \"%Y-%m-%d %H:%M:%S\"))].sort_values(\"fecha_inicio\").reset_index(drop = True)\n",
    "        ## si en vhc no existe el dato, vamos a buscarlo a evento telemetría\n",
    "        cursor = conn_sql.cursor()\n",
    "        # si el movil no está en vhc (df vacío), nos saltamos el dato\n",
    "        try:\n",
    "            a = pd.isna(aux.iloc[0][\"odo_inicio_gps\"]) # si aquí hay un error, significa que el df aux es vacío, es decir, el dato que buscamos no está en vhc\n",
    "            # si a es true, debo ingresar a query_eventos\n",
    "            # si a es false, no ingreso a query eventos\n",
    "            # si hay un error, a no tiene valor, por lo que hay que asignárselo en el except\n",
    "            # en dicho caso, el valor que se le asigna a a es irrelevante, ya que el error\n",
    "            # implica que aux es vacío, por lo que sí o sí se entrará a quey_eventos.\n",
    "            # Arbitrariamente la asignaré a false \n",
    "        except:\n",
    "            a = False\n",
    "        if aux.empty or a:\n",
    "            command_set_timezone = '''\n",
    "            set time zone 'America/Santiago'\n",
    "            '''    \n",
    "            query_eventos = '''\n",
    "            select v.nombre \n",
    "            ,et.fecha_evento\n",
    "            ,(et.atributos::json-> 'senial'->>'odom_km')::decimal as odometro_gps\n",
    "            ,case\n",
    "                when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),12,1) = '2' then to_timestamp(concat(et.fecha_evento::date + 1, ' 00:00:00'), 'YYYY-MM-DD HH24:MI:SS') - et.fecha_evento\n",
    "                when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),12,1) = '0' then et.fecha_evento - to_timestamp(concat(et.fecha_evento::date    , ' 00:00:00'), 'YYYY-MM-DD HH24:MI:SS')\n",
    "            --    when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),13,1) = '0' then to_timestamp(concat(et.fecha_evento::date, ' 21:00:00'), 'YYYY-MM-DD HH24:MI:SS') - et.fecha_evento\n",
    "            --    when substring(to_char(et.fecha_evento, 'YYYY-MM-DD HH24:MI:SS'),13,1) = '1' then et.fecha_evento - to_timestamp(concat(et.fecha_evento::date    , ' 21:00:00'), 'YYYY-MM-DD HH24:MI:SS')\n",
    "            end diferencia_medianoche\n",
    "            from evento_telemetria et \n",
    "            left join vehiculo v on et.vehiculo_id =v.id \n",
    "            where et.fecha_evento >= '{}' and et.fecha_evento < '{}'\n",
    "            and v.nombre = '{}'\n",
    "            order by diferencia_medianoche\n",
    "            '''.format(str(row[\"viaje_fecha_inicio_real\"].date()) + \" 23:50:00\", str(row[\"viaje_fecha_termino_real\"].date()) + \" 00:10:00\", row[\"movil_numero_interno\"])#format(str(row[\"fecha_inicio_real\"].date()) + \" 20:50:00\", str(row[\"fecha_inicio_real\"].date()) + \" 21:10:00\", row[\"numero_interno\"])\n",
    "            # .format(str(row[\"fecha_inicio_real\"].date()) + \" 23:50:00\", str(row[\"fecha_termino_real\"].date()) + \" 00:10:00\", row[\"numero_interno\"])\n",
    "            cursor.execute(command_set_timezone)\n",
    "            df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
    "            cursor.close()\n",
    "                # me quedo con todos los registros que sí tienen odometro gps\n",
    "            df_eventos_filtrado = df_eventos[pd.isna(df_eventos[\"odometro_gps\"]) == False]\n",
    "            # si al aplicar el filtro el df queda vacío, no hay odómetro, por lo que guardamos None\n",
    "            if df_eventos_filtrado.empty:\n",
    "                lista_odometros_medianoche_gps_fin.append(None)\n",
    "                fuente_odometro_medianoche_gps.append(None)\n",
    "                hora_evento_gps.append(None)\n",
    "            else:\n",
    "                lista_odometros_medianoche_gps_fin.append(df_eventos_filtrado.iloc[0][\"odometro_gps\"])\n",
    "                fuente_odometro_medianoche_gps.append(\"et\")\n",
    "                hora_evento_gps.append(df_eventos_filtrado.iloc[0][\"fecha_evento\"])\n",
    "        else:\n",
    "            lista_odometros_medianoche_gps_fin.append(aux.iloc[0][\"odo_inicio_gps\"])\n",
    "            fuente_odometro_medianoche_gps.append(\"vhc\")\n",
    "            hora_evento_gps.append(pd.to_datetime(fecha_fin + \" 00:00:00\"))\n",
    "        ids.append(row[\"viaje_id\"])\n",
    "        moviles.append(row[\"movil_numero_interno\"])\n",
    "        #ids.append(row[\"id\"])\n",
    "        #moviles.append(row[\"numero_interno\"])\n",
    "        \n",
    "    #data_medianoche = {'nombre': moviles, 'odometros_medianoche_gps_dia_inicio': lista_odometros_medianoche_odo_inicio_gps, 'odometros_medianoche_gps_dia_termino': lista_odometros_medianoche_gps_fin}\n",
    "    data_medianoche_gps = {'viaje_id':ids, 'movil_numero_interno': moviles, 'odometro_medianoche_gps': lista_odometros_medianoche_gps_fin, 'fuente_odometro_medianoche_gps':fuente_odometro_medianoche_gps, 'hora_evento_gps_medianoche':hora_evento_gps}\n",
    "    df_medianoche_gps = pd.DataFrame(data_medianoche_gps)\n",
    "    return df_medianoche_gps\n",
    "    #df_medianoche[\"hora_evento_gps_medianoche\"] = df_medianoche[\"hora_evento_gps_medianoche\"].apply(lambda x: x.tz_localize(None) if pd.isna(x) == False else x)\n",
    "    #df_medianoche[\" materi"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Unir df de viajes con df de odometros medianoche"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unir_dataframes(df_con_obs, df_odometro_medianoche):\n",
    "    # df_odometro_medianoche = df_odometro_medianoche.drop(columns = df_odometro_medianoche.columns[1:-2])#, inplace = True)\n",
    "    df_merged = pd.merge(df_con_obs, df_odometro_medianoche, \"left\", on = [\"viaje_id\", \"movil_numero_interno\"])\n",
    "    return df_merged"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Separar los viajes que corresponden en 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generar_nuevos_registros(df):\n",
    "    dff = copy.deepcopy(df)\n",
    "    dff[\"tipo_corte\"] = dff.apply(lambda x: \"inicio\" if x.flag_real == 1 else None, axis = 1)\n",
    "    #dff[\"km_dia\"] = dff[\"odometro_medianoche\"] - dff[\"km_inicial_can\"]\n",
    "    for index, row in dff.iterrows():\n",
    "        if row[\"flag_real\"] == 1:\n",
    "            dff.loc[len(dff)] = row.tolist()[:-7] + [row[\"odometro_medianoche_gps\"], row[\"fuente_odometro_medianoche_gps\"], row[\"hora_evento_gps_medianoche\"], row[\"odometro_medianoche_can\"], row[\"fuente_odometro_medianoche_can\"], row[\"hora_evento_can_medianoche\"],\"fin\"]\n",
    "    return dff"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Etiqueta la fuente del dato de odometro medianoche disponible"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "def etiquetar_corte(x):\n",
    "    if x.flag_real == 1 and pd.isna(x.odometro_medianoche_gps) == False and pd.isna(x.odometro_medianoche_can) == False:\n",
    "        x.etiqueta_corte = \"Existe gps y existe can\"\n",
    "    elif x.flag_real == 1 and pd.isna(x.odometro_medianoche_gps) == False and pd.isna(x.odometro_medianoche_can) == True:\n",
    "        x.etiqueta_corte = \"Existe gps y faltante can\"\n",
    "    elif x.flag_real == 1 and pd.isna(x.odometro_medianoche_gps) == True and pd.isna(x.odometro_medianoche_can) == False:\n",
    "        x.etiqueta_corte = \"Faltante gps\"\n",
    "    elif x.flag_real == 1 and pd.isna(x.odometro_medianoche_gps) == True and pd.isna(x.odometro_medianoche_can) == True:\n",
    "        x.etiqueta_corte = \"Faltante gps y faltante can\"\n",
    "    else:\n",
    "        x.etiqueta_corte = None\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Seleccionar km viajes en servicio\n",
    "def seleccionar_km_servicio(x):\n",
    "    if x.etiqueta_corte == None:\n",
    "        if x.etiqueta == 'Existe gps y existe can':\n",
    "            fuentes = {'CAN':float(x.viaje_distancia_can),'GPS':float(x.viaje_distancia_gps)}\n",
    "            max_key = max(fuentes, key=lambda key: fuentes[key])\n",
    "            x.km_seleccionado = max(float(x.viaje_distancia_can),float(x.viaje_distancia_gps))\n",
    "            x.km_servicio_dia = x.km_seleccionado\n",
    "            if max_key == 'CAN':\n",
    "                x.fuente_km_seleccionado = \"CAN\"\n",
    "            else:\n",
    "                x.fuente_km_seleccionado = \"GPS\"\n",
    "\n",
    "        elif x.etiqueta == 'Existe gps y faltante can':\n",
    "            x.km_seleccionado = float(x.viaje_distancia_gps)\n",
    "            x.km_servicio_dia = x.km_seleccionado\n",
    "            x.fuente_km_seleccionado = \"GPS\"\n",
    "\n",
    "\n",
    "        elif x.etiqueta == 'Faltante gps':\n",
    "            x.km_seleccionado = float(x.viaje_distancia_can)\n",
    "            x.km_servicio_dia = x.km_seleccionado\n",
    "            x.fuente_km_seleccionado = \"CAN\"\n",
    "        else:\n",
    "            pass\n",
    "            \n",
    "            #return x\n",
    "\n",
    "    elif x.etiqueta_corte != None:\n",
    "        if x.etiqueta == 'Existe gps y existe can':\n",
    "            if x.etiqueta_corte == 'Existe gps y existe can':\n",
    "                fuentes = {'CAN':float(x.viaje_distancia_can),'GPS':float(x.viaje_distancia_gps)}\n",
    "                max_key = max(fuentes, key=lambda key: fuentes[key])\n",
    "                x.km_seleccionado = max(float(x.viaje_distancia_can),float(x.viaje_distancia_gps))\n",
    "                if max_key == 'CAN':\n",
    "                    if x.tipo_corte == 'inicio':\n",
    "                        x.km_servicio_dia = x.odometro_medianoche_can - x.viaje_km_inicial_can\n",
    "                    else:\n",
    "                        x.km_servicio_dia = x.viaje_km_final_can - x.odometro_medianoche_can\n",
    "                    x.fuente_km_seleccionado = \"CAN\"\n",
    "                else:\n",
    "                    if x.tipo_corte == 'inicio':\n",
    "                        x.km_servicio_dia = x.odometro_medianoche_gps - x.viaje_km_inicial_gps\n",
    "                    else:\n",
    "                        x.km_servicio_dia = x.viaje_km_final_gps - x.odometro_medianoche_gps\n",
    "                    x.fuente_km_seleccionado = \"GPS\"\n",
    "\n",
    "            elif x.etiqueta_corte == 'Existe gps y faltante can':\n",
    "                x.km_seleccionado = float(x.viaje_distancia_gps)\n",
    "                if x.tipo_corte == 'inicio':\n",
    "                    x.km_servicio_dia = x.odometro_medianoche_gps - x.viaje_km_inicial_gps\n",
    "                else:\n",
    "                    x.km_servicio_dia = x.viaje_km_final_gps - x.odometro_medianoche_gps\n",
    "                x.fuente_km_seleccionado = \"GPS\"\n",
    "\n",
    "            elif x.etiqueta_corte == 'Faltante gps':\n",
    "                x.km_seleccionado = float(x.viaje_distancia_can)\n",
    "                if x.tipo_corte == 'inicio':\n",
    "                    x.km_servicio_dia = x.odometro_medianoche_can - x.viaje_km_inicial_can\n",
    "                else:\n",
    "                    x.km_servicio_dia = x.viaje_km_final_can - x.odometro_medianoche_can\n",
    "                x.fuente_km_seleccionado = \"CAN\"\n",
    "            else :\n",
    "                x.km_seleccionado = max(float(x.viaje_distancia_can),float(x.viaje_distancia_gps))\n",
    "                x.km_servicio_dia = None # más adelante, en este punto se repartirá el km de manera proporcional\n",
    "                fuentes = {'CAN':float(x.viaje_distancia_can),'GPS':float(x.viaje_distancia_gps)}\n",
    "                max_key = max(fuentes, key=lambda key: fuentes[key])\n",
    "                if max_key == 'CAN':\n",
    "                    x.fuente_km_seleccionado = \"CAN\"\n",
    "                else:\n",
    "                    x.fuente_km_seleccionado = \"GPS\"\n",
    "\n",
    "\n",
    "        elif x.etiqueta == 'Existe gps y faltante can':\n",
    "            if x.etiqueta_corte == 'Existe gps y faltante can' or x.etiqueta_corte == 'Existe gps y existe can':\n",
    "                x.km_seleccionado = float(x.viaje_distancia_gps)\n",
    "                if x.tipo_corte == 'inicio':\n",
    "                    x.km_servicio_dia = x.odometro_medianoche_gps - x.viaje_km_inicial_gps\n",
    "                else:\n",
    "                    x.km_servicio_dia = x.viaje_km_final_gps - x.odometro_medianoche_gps\n",
    "                x.fuente_km_seleccionado = \"GPS\"\n",
    "            else:\n",
    "                x.km_seleccionado = float(x.viaje_distancia_gps)\n",
    "                x.km_servicio_dia = None\n",
    "                x.fuente_km_seleccionado = \"GPS\"\n",
    "                \n",
    "        elif x.etiqueta == 'Faltante gps':\n",
    "            if x.etiqueta_corte == 'Faltante gps' or x.etiqueta_corte == 'Existe gps y existe can':\n",
    "                x.km_seleccionado = float(x.viaje_distancia_can)\n",
    "                if x.tipo_corte == 'inicio':\n",
    "                    x.km_servicio_dia = x.odometro_medianoche_can - x.viaje_km_inicial_can\n",
    "                else:\n",
    "                    x.km_servicio_dia = x.viaje_km_final_can - x.odometro_medianoche_can\n",
    "                x.fuente_km_seleccionado = \"CAN\"\n",
    "            else:\n",
    "                x.km_seleccionado = float(x.viaje_distancia_can)\n",
    "                x.km_servicio_dia = None\n",
    "                x.fuente_km_seleccionado = \"CAN\"\n",
    "        else:\n",
    "            pass\n",
    "\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "def errores_inicio_y_fin_viajes(x):\n",
    "    if x.flag_real == 1 and x.viaje_fecha_termino_real.date() < x.viaje_fecha_termino.date():\n",
    "        x.error_odometro_medianoche = \"Término real prematuro\"\n",
    "    elif x.flag_real == 1 and x.viaje_fecha_termino.date() < x.viaje_fecha_termino_real.date():\n",
    "        x.error_odometro_medianoche = \"Término real tardío\"\n",
    "    elif x.flag_real == 1 and x.viaje_fecha_inicio_real.date() < x.viaje_fecha_inicio.date():\n",
    "        x.error_odometro_medianoche = \"Inicio real prematuro\"\n",
    "    elif x.flag_real == 1 and x.viaje_fecha_inicio.date() < x.viaje_fecha_inicio_real.date():\n",
    "        x.error_odometro_medianoche = \"Inicio real tardío\"\n",
    "    return x"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ETL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\3763490519.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df = pd.read_sql(qr.query_viajes_bidb(str(inicio_d), str(fin_d)), conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\3763490519.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_3= pd.read_sql(qr.query_observaciones(str(inicio_d), str(fin_d)), conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\737581636.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n",
      "C:\\Users\\Tomas Retamal\\AppData\\Local\\Temp\\ipykernel_2396\\2136813667.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_eventos = pd.read_sql(query_eventos, conn_sql)\n"
     ]
    }
   ],
   "source": [
    "df_con_obs = obtener_viajes_con_obs(str(inicio_d), str(fin_d))\n",
    "df_dos_dias = viajes_dos_dias(df_con_obs)\n",
    "# estas siguientes dos lineas no recuerdo porque las agregué, ahora dudo que sirvan de algo así que las dejaré comentadas\n",
    "# df_dos_dias = copy.deepcopy(df_dos_dias[pd.isna(df_dos_dias[\"numero_interno\"]) == False]) \n",
    "# df_dos_dias = copy.deepcopy(df_dos_dias[df_dos_dias[\"numero_interno\"].str.startswith(\"BE\") == False])\n",
    "df_odometro_medianoche_can = odometro_medianoche_can(df_dos_dias, str(inicio_d), str(fin_d))\n",
    "df_odometro_medianoche_gps = odometro_medianoche_gps(df_dos_dias, str(inicio_d), str(fin_d))\n",
    "df_odometro_medianoche = pd.merge(df_odometro_medianoche_gps, df_odometro_medianoche_can, how = 'outer', on = [\"viaje_id\", \"movil_numero_interno\"])\n",
    "df_unido = unir_dataframes(df_con_obs, df_odometro_medianoche)\n",
    "df_nuevos_registros = generar_nuevos_registros(df_unido)\n",
    "df_nuevos_registros[\"etiqueta_corte\"] = None\n",
    "df_nuevos_registros_ = df_nuevos_registros.apply(lambda x: etiquetar_corte(x), axis = 1)\n",
    "df_nuevos_registros_[\"km_seleccionado\"] = None\n",
    "df_nuevos_registros_[\"km_servicio_dia\"] = None\n",
    "df_nuevos_registros_[\"fuente_km_seleccionado\"] = None\n",
    "df_nuevos_registros_n = df_nuevos_registros_.apply(lambda x: seleccionar_km_servicio(x), axis = 1)\n",
    "df_nuevos_registros_n[\"fecha_km_servicio_dia\"] = df_nuevos_registros_n.apply(lambda x: x.viaje_fecha_inicio_real.date() if x.tipo_corte == \"inicio\" else x.viaje_fecha_termino_real.date() if x.tipo_corte == \"fin\" else inicio_d, axis = 1)\n",
    "df_nuevos_registros_n[\"id_registro\"] = df_nuevos_registros_n.apply(lambda x: str(x.viaje_id) + \"1\" if x.tipo_corte == \"inicio\" else str(x.viaje_id) + \"2\" if x.tipo_corte == \"fin\" else str(x.viaje_id) + \"0\", axis = 1)\n",
    "df_nuevos_registros_n[\"error_odometro_medianoche\"] = None\n",
    "df_nuevos_registros_n = df_nuevos_registros_n.apply(lambda x: errores_inicio_y_fin_viajes(x), axis = 1)\n",
    "df_nuevos_registros_n[\"fecha_analisis\"] = inicio_d"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## DF final separado"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_nuevos_registros_n = df_nuevos_registros_n.reindex(columns = [\n",
    "    \"id_registro\",\n",
    "    \"fecha_km_servicio_dia\",\n",
    "    \"flag_planificado\",\n",
    "    \"flag_real\",\n",
    "    \"tipo_corte\",\n",
    "    \"viaje_id\",\n",
    "    \"movil_numero_interno\",\n",
    "    \"sucursal_viaje\",\n",
    "    \"descripcion_centro_costo\",\n",
    "    \"servicio_historico_alias\",\n",
    "    \"observacion\",\n",
    "    \"viaje_fecha_inicio\",\n",
    "    \"viaje_fecha_termino\",\n",
    "    \"viaje_fecha_inicio_real\",\n",
    "    \"viaje_fecha_termino_real\",\n",
    "    \"viaje_estado\",\n",
    "    \"etiqueta\",\n",
    "    \"etiqueta_corte\",\n",
    "    \"viaje_km_inicial_can\",\n",
    "    \"viaje_km_final_can\",\n",
    "    \"viaje_distancia_can\",\n",
    "    \"odometro_medianoche_can\",\n",
    "    \"fuente_odometro_medianoche_can\",\n",
    "    \"hora_evento_can_medianoche\",\n",
    "    \"viaje_km_inicial_gps\",\n",
    "    \"viaje_km_final_gps\",\n",
    "    \"viaje_distancia_gps\",\n",
    "    \"odometro_medianoche_gps\",\n",
    "    \"fuente_odometro_medianoche_gps\",\n",
    "    \"hora_evento_gps_medianoche\",\n",
    "    \"km_seleccionado\",\n",
    "    \"km_servicio_dia\",\n",
    "    \"error_odometro_medianoche\",\n",
    "    \"fuente_km_seleccionado\",\n",
    "    \"fecha_analisis\",\n",
    "    \"fecha_creacion\",\n",
    "    \"momento_cambio_movil\",\n",
    "    \"viaje_confirmacion\",\n",
    "    \"tipo_servicio\",\n",
    "    \"viaje_fecha_inicio_gps\",\n",
    "    \"viaje_fecha_termino_gps\",\n",
    "    \"viaje_fecha_inicio_conductor\",\n",
    "    \"viaje_fecha_termino_conductor\",\n",
    "    \"viaje_fecha_inicio_administrador\",\n",
    "    \"viaje_fecha_termino_adminiostrador\"\n",
    "])\n",
    "df_nuevos_registros_n = df_nuevos_registros_n.rename(columns={'fecha_creacion':'fecha_creacion_observacion'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_nuevos_registros_n = df_nuevos_registros_n.replace({np.NaN:None})\n",
    "df_nuevos_registros_n[\"flag_planificado\"] = df_nuevos_registros_n[\"flag_planificado\"].apply(lambda x: \"True\" if x == 1 else \"False\")\n",
    "df_nuevos_registros_n[\"flag_real\"] = df_nuevos_registros_n[\"flag_real\"].apply(lambda x: \"True\" if x == 1 else \"False\")\n",
    "df_nuevos_registros_n[\"viaje_confirmacion\"] = df_nuevos_registros_n[\"viaje_confirmacion\"].apply(lambda x: \"True\" if x == True else \"False\")\n",
    "#df_nuevos_registros_n = copy.deepcopy(df_nuevos_registros_n[df_nuevos_registros_n[\"momento_cambio_movil\"] != \"Durante el viaje\"])"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Crear tabla kilometrajes servicio diarios auxiliar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "#try:    \n",
    "#    conn_sql = psycopg2.connect(user = \"paul_bello\",\n",
    "#                                password = \"UAOZQ2Rr4t\",\n",
    "#                                host = \"192.168.40.239\",\n",
    "#                                port = \"5432\",\n",
    "#                                database = \"bidb\",\n",
    "#                                options=\"-c search_path=dbo,taller\")\n",
    "#    \n",
    "#    print('Conexión exitosa')\n",
    "#except: \n",
    "#    print('Conexión fallida')\n",
    "#cursor = conn_sql.cursor()\n",
    "#query_crear = '''\n",
    "#CREATE TABLE flota_pbello.bh_resumen_diario_km_servicio_auxiliar(\n",
    "#    id INTEGER PRIMARY KEY,\n",
    "#    )\n",
    "#'''\n",
    "#query_alter = '''\n",
    "#    ALTER TABLE flota_pbello.bh_kilometrajes_servicio_dia_auxiliar\n",
    "#    ADD COLUMN fecha_analisis DATE\n",
    "#'''\n",
    "##query_crear = ''' \n",
    "##    CREATE TABLE flota_pbello.bh_kilometrajes_servicio_dia_auxiliar (\n",
    "##    id_registro INTEGER PRIMARY KEY,\n",
    "##    fecha_km_servicio_dia DATE,\n",
    "##    flag_planificado BOOLEAN,\n",
    "##    flag_real BOOLEAN,\n",
    "##    tipo_corte VARCHAR,\n",
    "##    id INTEGER,\n",
    "##    numero_interno VARCHAR,\n",
    "##    sucursal VARCHAR,\n",
    "##    ceco VARCHAR,\n",
    "##    comercial VARCHAR,\n",
    "##    alias VARCHAR,\n",
    "##    observacion TEXT,\n",
    "##    fecha_inicio TIMESTAMP,\n",
    "##    fecha_termino TIMESTAMP,\n",
    "##    fecha_inicio_real TIMESTAMP,\n",
    "##    fecha_termino_real TIMESTAMP,\n",
    "##    estado VARCHAR,\n",
    "##    etiqueta VARCHAR,\n",
    "##    etiqueta_corte VARCHAR,\n",
    "##    km_inicial_can FLOAT,\n",
    "##    km_final_can FLOAT,\n",
    "##    distancia_can FLOAT,\n",
    "##    odometro_medianoche_can FLOAT,\n",
    "##    fuente_odometro_medianoche_can VARCHAR,\n",
    "##    hora_evento_can_medianoche TIMESTAMP,\n",
    "##    km_inicial_gps FLOAT,\n",
    "##    km_final_gps FLOAT,\n",
    "##    distancia_gps FLOAT,\n",
    "##    odometro_medianoche_gps FLOAT,\n",
    "##    fuente_odometro_medianoche_gps VARCHAR,\n",
    "##    hora_evento_gps_medianoche TIMESTAMP,\n",
    "##    km_seleccionado FLOAT,\n",
    "##    km_servicio_dia FLOAT,\n",
    "##    error_odometro_medianoche VARCHAR,\n",
    "##    fuente_km_seleccionado VARCHAR\n",
    "##);\n",
    "###'''\n",
    "#cursor.execute(query_alter)\n",
    "#conn_sql.commit()\n",
    "#cursor.close()\n",
    "#conn_sql.close()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Insertar datos en tabla creada en celda anterior"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [],
   "source": [
    "import psycopg2\n",
    "import numpy\n",
    "from psycopg2.extensions import register_adapter, AsIs\n",
    "def addapt_numpy_float64(numpy_float64):\n",
    "    return AsIs(numpy_float64)\n",
    "def addapt_numpy_int64(numpy_int64):\n",
    "    return AsIs(numpy_int64)\n",
    "register_adapter(numpy.float64, addapt_numpy_float64)\n",
    "register_adapter(numpy.int64, addapt_numpy_int64)\n",
    "psycopg2.extensions.register_adapter(np.int64, psycopg2._psycopg.AsIs)\n",
    "\n",
    "\n",
    "conn_sql = psycopg2.connect(user = \"paul_bello\",\n",
    "                            password = \"UAOZQ2Rr4t\",\n",
    "                            host = \"192.168.40.239\",\n",
    "                            port = \"5432\",\n",
    "                            database = \"bidb\",\n",
    "                            options=\"-c search_path=dbo,taller\")\n",
    "cursor = conn_sql.cursor()\n",
    "query_delete = f'''\n",
    "    DELETE FROM flota_pbello.bh_kilometrajes_servicio_dia_auxiliar WHERE fecha_analisis = '{str(inicio_d)}';\n",
    "    '''\n",
    "query_alter = '''\n",
    "    ALTER TABLE flota_pbello.bh_kilometrajes_servicio_dia_auxiliar\n",
    "    DROP COLUMN ceco;\n",
    "'''\n",
    "cursor.execute(query_delete)#, tuple(list(df_nuevos_registros_n.iloc[i])))  \n",
    "for i in range(len(df_nuevos_registros_n)):\n",
    "    query_insert ='''\n",
    "    INSERT INTO flota_pbello.bh_kilometrajes_servicio_dia_auxiliar (\n",
    "    id_registro,\n",
    "    fecha_km_servicio_dia,\n",
    "    flag_planificado,\n",
    "    flag_real,\n",
    "    tipo_corte,\n",
    "    id,\n",
    "    numero_interno,\n",
    "    sucursal,\n",
    "    comercial,\n",
    "    alias,\n",
    "    observacion,\n",
    "    fecha_inicio,\n",
    "    fecha_termino,\n",
    "    fecha_inicio_real,\n",
    "    fecha_termino_real,\n",
    "    estado,\n",
    "    etiqueta,\n",
    "    etiqueta_corte,\n",
    "    km_inicial_can,\n",
    "    km_final_can,\n",
    "    distancia_can,\n",
    "    odometro_medianoche_can,\n",
    "    fuente_odometro_medianoche_can,\n",
    "    hora_evento_can_medianoche,\n",
    "    km_inicial_gps,\n",
    "    km_final_gps,\n",
    "    distancia_gps,\n",
    "    odometro_medianoche_gps,\n",
    "    fuente_odometro_medianoche_gps,\n",
    "    hora_evento_gps_medianoche,\n",
    "    km_seleccionado,\n",
    "    km_servicio_dia,\n",
    "    error_odometro_medianoche,\n",
    "    fuente_km_seleccionado,\n",
    "    fecha_analisis,\n",
    "    fecha_creacion_observacion,\n",
    "    momento_cambio_movil,\n",
    "    confirmacion,\n",
    "    tipo_servicio,\n",
    "    viaje_fecha_inicio_gps,\n",
    "    viaje_fecha_termino_gps,\n",
    "    viaje_fecha_inicio_conductor,\n",
    "    viaje_fecha_termino_conductor,\n",
    "    viaje_fecha_inicio_administrador,\n",
    "    viaje_fecha_termino_administrador)\n",
    "    VALUES (\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s,\n",
    "        %s,%s,%s,%s,%s)\n",
    "    '''\n",
    "    cursor.execute(query_insert, tuple(list(df_nuevos_registros_n.iloc[i])))\n",
    "    if i % 100 == 0:\n",
    "        conn_sql.commit()      \n",
    "#cursor.execute(query_alter,  tuple(list(df_nuevos_registros_n.iloc[i])))\n",
    "conn_sql.commit()\n",
    "cursor.close()\n",
    "conn_sql.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.12 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "38259bfb52411bd61fa78eb6a6bb5252818531c9d436c3f144f501e1e063a387"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
